# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 768)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Logo = QtWidgets.QLabel(self.centralwidget)
        self.Logo.setGeometry(QtCore.QRect(1265, 1, 100, 100))
        self.Logo.setText("")
        self.Logo.setPixmap(QtGui.QPixmap("logo1.png"))
        self.Logo.setObjectName("Logo")
        self.Plotting = MyWidget(self.centralwidget)
        self.Plotting.setGeometry(QtCore.QRect(0, 70, 551, 251))
        self.Plotting.setStyleSheet("")
        self.Plotting.setObjectName("Plotting")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 0, 944, 66))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Latitude_1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.Latitude_1.setText("")
        self.Latitude_1.setObjectName("Latitude_1")
        self.gridLayout.addWidget(self.Latitude_1, 0, 0, 1, 1)
        self.Latitude_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.Latitude_2.setText("")
        self.Latitude_2.setObjectName("Latitude_2")
        self.gridLayout.addWidget(self.Latitude_2, 0, 1, 1, 1)
        self.Latitude_3 = QtWidgets.QLineEdit(self.layoutWidget)
        self.Latitude_3.setText("")
        self.Latitude_3.setObjectName("Latitude_3")
        self.gridLayout.addWidget(self.Latitude_3, 0, 2, 1, 1)
        self.Latitude_4 = QtWidgets.QLineEdit(self.layoutWidget)
        self.Latitude_4.setText("")
        self.Latitude_4.setObjectName("Latitude_4")
        self.gridLayout.addWidget(self.Latitude_4, 0, 3, 1, 1)
        self.Latitude_5 = QtWidgets.QLineEdit(self.layoutWidget)
        self.Latitude_5.setText("")
        self.Latitude_5.setObjectName("Latitude_5")
        self.gridLayout.addWidget(self.Latitude_5, 0, 4, 1, 1)
        self.Latitude_6 = QtWidgets.QLineEdit(self.layoutWidget)
        self.Latitude_6.setText("")
        self.Latitude_6.setObjectName("Latitude_6")
        self.gridLayout.addWidget(self.Latitude_6, 0, 5, 1, 1)
        self.Longitude_1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.Longitude_1.setText("")
        self.Longitude_1.setObjectName("Longitude_1")
        self.gridLayout.addWidget(self.Longitude_1, 1, 0, 1, 1)
        self.Longitude_2 = QtWidgets.QLineEdit(self.layoutWidget)
        self.Longitude_2.setText("")
        self.Longitude_2.setObjectName("Longitude_2")
        self.gridLayout.addWidget(self.Longitude_2, 1, 1, 1, 1)
        self.Longitude_3 = QtWidgets.QLineEdit(self.layoutWidget)
        self.Longitude_3.setText("")
        self.Longitude_3.setObjectName("Longitude_3")
        self.gridLayout.addWidget(self.Longitude_3, 1, 2, 1, 1)
        self.Longitude_4 = QtWidgets.QLineEdit(self.layoutWidget)
        self.Longitude_4.setText("")
        self.Longitude_4.setObjectName("Longitude_4")
        self.gridLayout.addWidget(self.Longitude_4, 1, 3, 1, 1)
        self.Longitude_5 = QtWidgets.QLineEdit(self.layoutWidget)
        self.Longitude_5.setText("")
        self.Longitude_5.setObjectName("Longitude_5")
        self.gridLayout.addWidget(self.Longitude_5, 1, 4, 1, 1)
        self.Longitude_6 = QtWidgets.QLineEdit(self.layoutWidget)
        self.Longitude_6.setText("")
        self.Longitude_6.setObjectName("Longitude_6")
        self.gridLayout.addWidget(self.Longitude_6, 1, 5, 1, 1)
        self.cam8 = App(self.centralwidget)
        self.cam8.setGeometry(QtCore.QRect(550, 70, 640, 480))
        self.cam8.setObjectName("cam8")
        self.PlotButton = QtWidgets.QPushButton(self.centralwidget)
        self.PlotButton.setGeometry(QtCore.QRect(426, 71, 38, 16))
        self.PlotButton.setObjectName("PlotButton")
        self.chgEnd = QtWidgets.QPushButton(self.centralwidget)
        self.chgEnd.setGeometry(QtCore.QRect(464, 71, 85, 16))
        self.chgEnd.setObjectName("chgEnd")
        self.Plotting.raise_()
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.Logo.raise_()
        self.cam8.raise_()
        self.PlotButton.raise_()
        self.chgEnd.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Latitude_1.setPlaceholderText(_translate("MainWindow", "Latitude"))
        self.Latitude_2.setPlaceholderText(_translate("MainWindow", "Latitude"))
        self.Latitude_3.setPlaceholderText(_translate("MainWindow", "Latitude"))
        self.Latitude_4.setPlaceholderText(_translate("MainWindow", "Latitude"))
        self.Latitude_5.setPlaceholderText(_translate("MainWindow", "Latitude"))
        self.Latitude_6.setPlaceholderText(_translate("MainWindow", "Latitude"))
        self.Longitude_1.setPlaceholderText(_translate("MainWindow", "Longitude"))
        self.Longitude_2.setPlaceholderText(_translate("MainWindow", "Longitude"))
        self.Longitude_3.setPlaceholderText(_translate("MainWindow", "Longitude"))
        self.Longitude_4.setPlaceholderText(_translate("MainWindow", "Longitude"))
        self.Longitude_5.setPlaceholderText(_translate("MainWindow", "Longitude"))
        self.Longitude_6.setPlaceholderText(_translate("MainWindow", "Longitude"))
        self.PlotButton.setText(_translate("MainWindow", "Plot"))
        self.chgEnd.setText(_translate("MainWindow", "Next Co-ods"))

from RPi_data import MyWidget
from cam8 import App
import xz_rc
